// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwucMLH0mfif263k7Z5D746ndNiWf_6So',
    appId: '1:560042388041:ios:ac7d310afdeb1b7c66ed98',
    messagingSenderId: '560042388041',
    projectId: 'fir-chat-23ab7',
    storageBucket: 'fir-chat-23ab7.appspot.com',
    iosClientId: '560042388041-dkgvpfvgdv2p3nhep39vksjaqkg3agbf.apps.googleusercontent.com',
    iosBundleId: 'com.massimilianoporzio.firebsaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwucMLH0mfif263k7Z5D746ndNiWf_6So',
    appId: '1:560042388041:ios:464f9ad1b3a89b7266ed98',
    messagingSenderId: '560042388041',
    projectId: 'fir-chat-23ab7',
    storageBucket: 'fir-chat-23ab7.appspot.com',
    iosClientId: '560042388041-2d3nb621cavhueeqvm7tsj2biu2g4mot.apps.googleusercontent.com',
    iosBundleId: 'com.massimilianoporzio.firebaseChat',
  );
}
